### ISSUE TITLE
Add workflow for pull requests

### ISSUE THREAD

**Issue by ryansonshine** [awslabs/aws-break-glass-role#3]
When a contributor makes a pull request, we want to be able to test the code in the PR while also avoiding running the integration tests for pull requests to reduce attack surface for bad actors.

**Comment by smguggen** [comment]
After reading [this](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) I'm thinking pull requests should be manually accepted before any workflows are run on them.
